### PR TITLE
Use BaseController instead of Store controller to adapt to changes in OFN

### PR DESCRIPTION
**Pull request by luisramos0**
We need to use BaseController and not StoreController. StoreController has been removed from OFN here: https://github.com/openfoodfoundation/openfoodnetwork/pull/6279/commits

### CODE REVIEW

**Review by mkllnk — CHANGES_REQUESTED** [review]
I don't think this works. I looked up what the StoreController used to provide and one example is `current_order` which is referenced in this code.

I can think of two options:

1. Import this code into OFN and refactor it properly there.
2. Add the helpers:
```rb
    include Spree::Core::ControllerHelpers::Order
```

**Comment by luisramos0** [comment]
I wonder what you mean by it doesnt work. Did you see 6279?

**Review by mkllnk — APPROVED** [review]
Ah, sorry!

I overlooked the fact that `::BaseController` does have those helpers. :facepalm: 

All good then, back to review.

**Comment by Matt-Yorkley** [comment]
Can we just bring all of the code in? https://github.com/openfoodfoundation/openfoodnetwork/issues/6421

**Comment by luisramos0** [comment]
I cant do that right now. So I'd prefer to merge this and unblock https://github.com/openfoodfoundation/openfoodnetwork/pull/6279

**Comment by luisramos0** [comment]
done in https://github.com/openfoodfoundation/openfoodnetwork/pull/6279/commits

**Pull request closed without merging**
